DELIMITER $$

CREATE FUNCTION f_CitasProximas(dias INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE total INT;

    SELECT COUNT(*) INTO total
    FROM Citas
    WHERE fecha_hora BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL dias DAY);
    
    RETURN total;
END$$

DELIMITER ;